LANG = {
	en : {
		editing : 'Editing',
		notSaved : 'Not saved',
		saved : 'Saved',
		unsavedConfirmation : 'You got unsaved changes on this file... Are you sure?',
		openFile : 'Open file',
		file : 'File',
		newFile : 'New file',
		newFolder : 'New folder',
		name : 'Name',
		open : 'Open',
		save : 'Save',
		saveAs : 'Save as',
		remove : 'Remove',
		rename : 'Rename',
		areYouSure : 'Are you sure?',
		newWindow : 'New window',
		closeWindow : 'Close window',
		edit : 'Edit',
		undo : 'Undo',
		redo : 'Redo',
		find : 'Find',
		findAndReplace : 'Replace',
		themes : 'Themes',
		underGPL : 'Under a GPL license'
	},
	es : {
		editing : 'Editando',
		notSaved : 'Sin guardar',
		saved : 'Guardado',
		unsavedConfirmation : 'Tienes cambios sin guardar en este fichero... ¿Estás seguro?',
		openFile : 'Abrir fichero',
		file : 'Fichero',
		newFile : 'Nuevo archivo',
		newFolder : 'Nueva carpeta',
		name : 'Nombre',
		open : 'Abrir',
		save : 'Guardar',
		saveAs : 'Guardar como',
		remove : 'Eliminar',
		rename : 'Cambiar nombre',
		areYouSure : '¿Estás seguro?',
		newWindow : 'Nueva ventana',
		closeWindow : 'Cerrar ventana',
		edit : 'Editar',
		undo : 'Deshacer',
		redo : 'Rehacer',
		find : 'Buscar',
		findAndReplace : 'Reemplazar',
		themes : 'Temas',
		underGPL : 'Bajo una licencia GPL'
	}
};
